export const TRANSACTION_TYPES = {
    ROOM_BOOKING: 1,
    EVENT_BOOKING: 2,
    MEMBERSHIP: 3,
    MAINTENANCE: 4,
    SUBSCRIPTION: 5,
    FINANCIAL_CHARGE: 6,
    FOOD_ORDER: 7,
    APPLIED_MEMBER: 8,
};
